export const categoryArray = [
    { id: 0, name: "Random", icon: "🔀" },
    { id: 9, name: "General Knowledge", icon: "💡" },
    { id: 10, name: "Entertainment: Books", icon: "📚" },
    { id: 11, name: "Entertainment: Film", icon: "🎥" },
    { id: 12, name: "Entertainment: Music", icon: "🎶" },
    { id: 13, name: "Entertainment: Musicals & Theatres", icon: "🎭" },
    { id: 14, name: "Entertainment: Television", icon: "📺" },
    { id: 15, name: "Entertainment: Video Games", icon: "🎮" },
    { id: 16, name: "Entertainment: Board Games", icon: "🎲" },
    { id: 17, name: "Science & Nature", icon: "🔬" },
    { id: 18, name: "Science: Computers", icon: "💻" },
    { id: 19, name: "Science: Mathematics", icon: "➗" },
    { id: 20, name: "Mythology", icon: "🏛️" },
    { id: 21, name: "Sports", icon: "🏀" },
    { id: 22, name: "Geography", icon: "🌍" },
    { id: 23, name: "History", icon: "📜" },
    { id: 24, name: "Politics", icon: "🗳️" },
    { id: 25, name: "Art", icon: "🎨" },
    { id: 26, name: "Celebrities", icon: "🌟" },
    { id: 27, name: "Animals", icon: "🐾" },
    { id: 28, name: "Vehicles", icon: "🚗" },
    { id: 29, name: "Entertainment: Comics", icon: "🦸" },
    { id: 30, name: "Science: Gadgets", icon: "🔧" },
    { id: 31, name: "Entertainment: Japanese Anime & Manga", icon: "🎌" },
    { id: 32, name: "Entertainment: Cartoon & Animations", icon: "🖍️" },
  ];